fix(wizer): enable `wasmtime/anyhow`
Enabling both `wasmtime` and `component-model` features fails with
regular `cargo build`.

Note, that this issue is not reproducible using `cargo test`, because
`wasmtime/anyhow` is unconditionally enabled in `dev-dependencies`

```
$ cargo build --features wasmtime,component-model
...
error[E0599]: no associated function or constant named `from_anyhow` found for struct `wasmtime::Error` in the current scope
  --> crates/wizer/src/component/wasmtime.rs:54:43
   |
54 |                 .map_err(wasmtime::Error::from_anyhow)
   |                                           ^^^^^^^^^^^ associated function or constant not found in `wasmtime::Error`

error[E0599]: no associated function or constant named `from_anyhow` found for struct `wasmtime::Error` in the current scope
  --> crates/wizer/src/component/wasmtime.rs:61:47
   |
61 |                     .map_err(wasmtime::Error::from_anyhow)
   |                                               ^^^^^^^^^^^ associated function or constant not found in `wasmtime::Error`
...
```

Signed-off-by: Roman Volosatovs <rvolosatovs@riseup.net>