Fix the version of mach2 in Cargo.toml
The toml file specifies version `0.4.1` instead of `0.4.2`.

Using version `0.4.1` produces a compile error:

```
error[E0432]: unresolved import `mach2::ndr`
  --> external/crate_index__wasmtime-runtime-20.0.2/src/sys/unix/machports.rs:44:12
   |
44 | use mach2::ndr::*;
   |            ^^^ could not find `ndr` in `mach2`
```

That's because `ndr` was added in version `0.4.2`.

Note that the lock file specifies version `0.4.2` which explains
why this error doesn't happen normally.